version: '3.8'

services:
  web:
    build: .
    container_name: restaurant_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - php_logs:/var/www/html/customerSide/logs
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=restaurantdb

  db:
    image: mysql:5.7
    container_name: restaurant_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurantdb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    volumes:
      - grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/var/lib/loki

  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - php_logs:/var/www/html/customerSide/logs  # ✅ Fix indentasi volume
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki

volumes:
  db_data:
  grafana_data:
  loki_data:
  php_logs:  # ✅ Volume yang sama untuk web & promtail
