name: Deploy Restaurant Website

on:
  push:
    branches:
      - main  # Jalankan saat ada push ke branch `main`
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Mengambil kode dari GitHub

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2  # Menjalankan Docker dengan BuildX

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/restaurant-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/restaurant-app:latest
